// Code generated by protoc-gen-go. DO NOT EDIT.
// source: store.proto

/*
Package store is a generated protocol buffer package.

It is generated from these files:
	store.proto

It has these top-level messages:
	StoreParams
	StoreTable
*/
package store

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type StoreParams struct {
	TableLen         *int32 `protobuf:"varint,1,opt,name=table_len" json:"table_len,omitempty"`
	MaxOutputBytes   *int32 `protobuf:"varint,2,opt,name=max_output_bytes" json:"max_output_bytes,omitempty"`
	RowBytes         *int32 `protobuf:"varint,3,opt,name=row_bytes" json:"row_bytes,omitempty"`
	TagBytes         *int32 `protobuf:"varint,4,opt,name=tag_bytes" json:"tag_bytes,omitempty"`
	SaltBytes        *int32 `protobuf:"varint,5,opt,name=salt_bytes" json:"salt_bytes,omitempty"`
	Salt             []byte `protobuf:"bytes,6,opt,name=salt" json:"salt,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *StoreParams) Reset()                    { *m = StoreParams{} }
func (m *StoreParams) String() string            { return proto.CompactTextString(m) }
func (*StoreParams) ProtoMessage()               {}
func (*StoreParams) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *StoreParams) GetTableLen() int32 {
	if m != nil && m.TableLen != nil {
		return *m.TableLen
	}
	return 0
}

func (m *StoreParams) GetMaxOutputBytes() int32 {
	if m != nil && m.MaxOutputBytes != nil {
		return *m.MaxOutputBytes
	}
	return 0
}

func (m *StoreParams) GetRowBytes() int32 {
	if m != nil && m.RowBytes != nil {
		return *m.RowBytes
	}
	return 0
}

func (m *StoreParams) GetTagBytes() int32 {
	if m != nil && m.TagBytes != nil {
		return *m.TagBytes
	}
	return 0
}

func (m *StoreParams) GetSaltBytes() int32 {
	if m != nil && m.SaltBytes != nil {
		return *m.SaltBytes
	}
	return 0
}

func (m *StoreParams) GetSalt() []byte {
	if m != nil {
		return m.Salt
	}
	return nil
}

type StoreTable struct {
	Params           *StoreParams `protobuf:"bytes,1,opt,name=params" json:"params,omitempty"`
	Table            []byte       `protobuf:"bytes,2,opt,name=table" json:"table,omitempty"`
	Idx              []int32      `protobuf:"varint,3,rep,name=idx" json:"idx,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *StoreTable) Reset()                    { *m = StoreTable{} }
func (m *StoreTable) String() string            { return proto.CompactTextString(m) }
func (*StoreTable) ProtoMessage()               {}
func (*StoreTable) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *StoreTable) GetParams() *StoreParams {
	if m != nil {
		return m.Params
	}
	return nil
}

func (m *StoreTable) GetTable() []byte {
	if m != nil {
		return m.Table
	}
	return nil
}

func (m *StoreTable) GetIdx() []int32 {
	if m != nil {
		return m.Idx
	}
	return nil
}

func init() {
	proto.RegisterType((*StoreParams)(nil), "store.StoreParams")
	proto.RegisterType((*StoreTable)(nil), "store.StoreTable")
}

func init() { proto.RegisterFile("store.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 179 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0xce, 0xc1, 0x0b, 0x82, 0x30,
	0x14, 0xc7, 0x71, 0xd6, 0x9c, 0xe0, 0x9b, 0x41, 0xbe, 0xd3, 0x8e, 0xe2, 0xc9, 0x93, 0x87, 0xfe,
	0x8e, 0x0e, 0x41, 0xdd, 0x65, 0xd2, 0x88, 0x40, 0x9b, 0x6c, 0x4f, 0xb2, 0x6b, 0x7f, 0x79, 0xf8,
	0x52, 0xe8, 0xb6, 0x7d, 0xc7, 0xf8, 0x7d, 0x40, 0x47, 0xf2, 0xc1, 0x35, 0x63, 0xf0, 0xe4, 0x51,
	0xf1, 0xa5, 0xfa, 0x08, 0xd0, 0x97, 0xe5, 0x74, 0xb6, 0xc1, 0x0e, 0x11, 0x0b, 0xc8, 0xc8, 0x76,
	0xbd, 0x6b, 0x7b, 0xf7, 0x34, 0xa2, 0x14, 0xb5, 0x42, 0x03, 0x87, 0xc1, 0xce, 0xad, 0x9f, 0x68,
	0x9c, 0xa8, 0xed, 0xde, 0xe4, 0xa2, 0xd9, 0xf1, 0x4b, 0x01, 0x59, 0xf0, 0xaf, 0x35, 0xc9, 0x2d,
	0x91, 0xbd, 0xaf, 0x29, 0xe1, 0x84, 0x00, 0xd1, 0xf6, 0xdb, 0x4f, 0xc5, 0x2d, 0x87, 0x64, 0x69,
	0x26, 0x2d, 0x45, 0x9d, 0x57, 0x27, 0x00, 0x36, 0x5c, 0x97, 0x65, 0xac, 0x20, 0x1d, 0x19, 0xc3,
	0xfb, 0xfa, 0x88, 0xcd, 0xcf, 0xfd, 0xcf, 0xdc, 0x83, 0x62, 0x26, 0x43, 0x72, 0xd4, 0x20, 0x1f,
	0xb7, 0xd9, 0xc8, 0x52, 0xd6, 0xea, 0x1b, 0x00, 0x00, 0xff, 0xff, 0x5f, 0x25, 0x7d, 0x98, 0xe7,
	0x00, 0x00, 0x00,
}
